name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Print Environment Info
        run: pnpm exec nx report
        shell: bash

      - name: Release packages
        run: pnpm exec nx release --skip-publish --verbose
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: redpill-ci
          GIT_AUTHOR_EMAIL: redpill-ci@redpill.ventures
          GIT_COMMITTER_NAME: redpill-ci
          GIT_COMMITTER_EMAIL: redpill-ci@redpill.ventures
          NX_SKIP_NX_CACHE: true

      - name: Publish to npm
        run: pnpm exec nx release publish --verbose
        shell: bash
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
