name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Print Environment Info
        run: pnpm exec nx report
        shell: bash

      - name: Build packages
        run: pnpm exec nx run-many -t build --verbose
        shell: bash

      ####################
      # DISABLED FOR NOW #
      ####################
      # - name: Release packages
      #   run: pnpm exec nx release --verbose
      #   shell: bash
      #   env:
      #     NPM_CONFIG_PROVENANCE: true
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      #     GIT_AUTHOR_NAME: redpill-ci
      #     GIT_AUTHOR_EMAIL: redpill-ci@redpill.ventures
      #     GIT_COMMITTER_NAME: redpill-ci
      #     GIT_COMMITTER_EMAIL: redpill-ci@redpill.ventures
